changes

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,180 @@
 #!/bin/sh
 
-# base on: 
+# based on: 
 # https://github.com/wlanslovenija/firmware-core/blob/master/scripts/build
-echo "Not yet implemented"
+
+BUILD_DIR=built_firmware
+
+log()
+{
+  echo "[PON firmware] build: $*"
+}
+
+
+openwrt_verify_architecture()
+{
+  local arch=$1
+  if [ ! -d ${workdir}/${BUILD_DIR}/openwrt/target/linux/${arch} ]; then
+    log "Invalid architecture '${arch}', aborting."
+    exit 1
+  fi
+
+  if [ ! -f ${workdir}/openwrt/configs/${arch} ]; then
+    log "Architecture missing configuration file, aborting."
+    exit 1
+  fi
+}
+
+openwrt_build_configure()
+{
+  local arch=$1
+  local kconfig=${workdir}/${BUILD_DIR}/openwrt/scripts/kconfig.pl
+  local config_dir=${workdir}/openwrt/configs
+  local config=${workdir}/${BUILD_DIR}/openwrt/config.${arch}
+  $kconfig 'm+' ${config_dir}/generic ${config_dir}/${arch} > ${config}
+
+  # Include all common packages
+  for pkg in ${all_packages}; do
+    echo "CONFIG_PACKAGE_${pkg}=y" >> ${config}
+  done
+
+  # Remove configuration file already present in the generic build dir
+  rm -f ${workdir}/${BUILD_DIR}/openwrt/.config
+}
+
+openwrt_builder_cleanup()
+{
+  local build_dir=$1
+  rm -rf ${build_dir}
+  exit
+}
+
+openwrt_builder()
+{
+  local arch=$1
+  local build_dir=${workdir}/${BUILD_DIR}/builder.${arch}.$$
+
+  # Make hardlinks to avoid space duplication but to still isolate builds
+  cp -lr ${workdir}/${BUILD_DIR}/openwrt ${build_dir}
+  
+  # Prepare configuration file and build the bastard
+  cd ${build_dir}
+  cp config.${arch} .config
+  make defconfig &> ${build_dir}/build.log
+  if [ "$?" != "0" ]; then
+    log "Default configuration preparation for '${arch}' has failed. See build.log for details!"
+    exit 1
+  fi
+
+  make V=99 &> ${build_dir}/build.log
+  if [ "$?" != "0" ]; then
+    log "Build for architecture '${arch}' has failed. See build.log for details!"
+    exit 1
+  fi
+
+  # Copy image builder and packages
+  log "Copying image builder and packages for '${arch}'..."
+  local release_dir=${workdir}/${BUILD_DIR}/release/${arch}
+  mkdir -p ${release_dir}
+  cp ${build_dir}/bin/${arch}/OpenWrt-ImageBuilder-*.tar.bz2 ${release_dir}/imagebuilder.${arch}.tar.bz2
+  cp -a ${build_dir}/bin/${arch}/packages ${release_dir}
+
+  # Cleanup things
+  openwrt_builder_cleanup ${build_dir}
+}
+
+
+
+##########################################
+##                                      ##
+##  Build code calling above functions  ##
+##                                      ##
+##########################################
+
+
+# Check for proper working directory
+log "Checking working directory..."
+if [[ ! -d scripts || ! -d openwrt ]]; then
+  log "Invalid working directory!"
+  exit 1
+fi
+
+if [[ ! -d build/openwrt ]]; then
+  log "Build directory is not prepared. Have you run ./scripts/prepare?"
+  exit 1
+fi
+
+override_architectures="$*"
+workdir=$(pwd)
+
+# Check architectures that we need to build
+all_architectures=$(cat openwrt/architectures)
+if [ -z "${override_architectures}" ]; then
+  architectures="${all_architectures}"
+else
+  architectures=""
+  for arch in $override_architectures; do
+    found=0
+    for sarch in $all_architectures; do
+      if [[ "$arch" == "$sarch" ]]; then
+        architectures="${architectures} ${arch}"
+        found=1
+        break
+      fi
+    done
+
+    if [[ $found == 0 ]]; then
+      log "ERROR: Invalid architecture '${arch}' specified."
+      exit 1
+    fi
+  done
+fi
+
+log "Will build for the following OpenWRT architectures:"
+for arch in $architectures; do
+  openwrt_verify_architecture $arch
+  log " * ${arch}"
+done
+
+# Check packages that we need to build
+log "Will build the following OpenWRT packages for ALL architectures:"
+all_packages=$(grep 'Package:' ${workdir}/${BUILD_DIR}/openwrt/feeds/peopleswifi.index | cut -d ':' -f 2)
+all_packages="${all_packages} $(cat openwrt/packages)"
+for pkg in $all_packages; do
+  log " * ${pkg}"
+done
+
+# Cleanup previous builder leftovers
+log "Cleaning up previous builder leftovers..."
+rm -rf ${workdir}/${BUILD_DIR}/builder.*
+rm -rf ${workdir}/${BUILD_DIR}/release
+
+# Generate build configurations
+log "Generating build configurations..."
+for arch in $architectures; do
+  openwrt_build_configure $arch
+done
+
+# Spawn builders
+log "Spawning builders..."
+builder_pids=""
+for arch in $architectures; do
+  openwrt_builder ${arch} &
+  bpid=$!
+  builder_pids="${builder_pids} ${bpid}"
+  
+  log " * ${arch} (${bpid})"
+done
+
+# Trap interruptions
+trap_handler()
+{
+  local pgid=$(ps -p $$ -o pgid="")
+  kill -- -${pgid}
+  exit
+}
+trap trap_handler INT QUIT TERM EXIT
+
+# Wait for builders
+log "Waiting for builders to finish building..."
+wait ${builder_pids}
diff --git a/prepare b/prepare
--- a/prepare
+++ b/prepare
@@ -1,13 +1,12 @@
 #!/bin/bash
 
-# sudomesh firmware prepare script
+# peopleswifi firmware prepare script
 # based on wlanslovenija prepare script
 
 
 BUILD_DIR=built_firmware
 
-echo "Checking dependencies"
-
+#echo "Checking dependencies"
 #if [ ! command -v quilt ]; then
 #  echo "quilt not found."
 #  exit 1
@@ -36,15 +35,26 @@ echo "OpenWRT revision: ${openwrt_rev}"
 echo "Checking out OpenWRT into ${BUILD_DIR}, this could take some time"
 
 OPENWRT_CHECKOUT_DIR=${workdir}/${BUILD_DIR}/openwrt
-rm -rf ${OPENWRT_CHECKOUT_DIR}
-svn co -q -r ${openwrt_rev} svn://svn.openwrt.org/openwrt/${openwrt_path} ${OPENWRT_CHECKOUT_DIR}
-
-echo "Purging .svn files from repository"
-find ${OPENWRT_CHECKOUT_DIR} -name .svn -type d -exec rm -rf "{}" \; 2>/dev/null
+if [ -f ${OPENWRT_CHECKOUT_DIR}/.success ]; then
+  echo "OpenWRT already checked out"
+else
+  svn status ${OPENWRT_CHECKOUT_DIR}
+  rm -rf ${OPENWRT_CHECKOUT_DIR}
+  svn co -q -r ${openwrt_rev} svn://svn.openwrt.org/openwrt/${openwrt_path} ${OPENWRT_CHECKOUT_DIR}
+  if [ $? -ne 0 ]; then
+    echo "Error during svn checkout of OpenWRT"
+    exit $?
+  else
+    # make a file indicating that this is a successfully checked out openwrt dir
+    touch ${OPENWRT_CHECKOUT_DIR}/.success
+  fi
+  echo "Purging .svn files from repository"
+  find ${OPENWRT_CHECKOUT_DIR} -name .svn -type d -exec rm -rf "{}" \; 2>/dev/null
+fi
 
 # Inject feeds and configurations
 echo "Configuring feeds"
-echo "src-git sudomesh git://github.com/sudomesh/openwrt-packages.git" > ${OPENWRT_CHECKOUT_DIR}/feeds.conf
+echo "src-git peopleswifi git://github.com/sudomesh/openwrt-packages.git" > ${OPENWRT_CHECKOUT_DIR}/feeds.conf
 echo "src-svn openwrt svn://svn.openwrt.org/openwrt/packages" >> ${OPENWRT_CHECKOUT_DIR}/feeds.conf
 echo "src-git routing git://github.com/openwrt-routing/packages.git" >> ${OPENWRT_CHECKOUT_DIR}/feeds.conf
 
@@ -59,7 +69,7 @@ cd ${OPENWRT_CHECKOUT_DIR}
 # Importing feeds
 echo "Importing feeds"
 ./scripts/feeds update -a > /dev/null
-./scripts/feeds install -a -p sudomesh
+./scripts/feeds install -a -p peopleswifi
 
 for package in $(cat ${workdir}/openwrt_config/packages); do
   ./scripts/feeds install ${package}
@@ -93,7 +103,6 @@ else
   done
 fi
 
-
 openwrt_verify_architecture()
 {
   local arch=$1
@@ -117,15 +126,15 @@ done
 
 # Check packages that we need to build
 echo "Configuring build for the following OpenWRT packages:"
-all_packages=$(grep 'Package:' ${workdir}/${BUILD_DIR}/openwrt/feeds/sudomesh.index | cut -d ':' -f 2)
+all_packages=$(grep 'Package:' ${workdir}/${BUILD_DIR}/openwrt/feeds/peopleswifi.index | cut -d ':' -f 2)
 all_packages="${all_packages} $(cat openwrt_config/packages)"
 for pkg in $all_packages; do
   echo " * ${pkg}"
 done
 
-echo "Cleaning up previous builder leftovers..."
-rm -rf ${workdir}/${BUILD_DIR}/builder.*
-rm -rf ${workdir}/${BUILD_DIR}/release
+#echo "Cleaning up previous builder leftovers..."
+#rm -rf ${workdir}/${BUILD_DIR}/builder.*
+#rm -rf ${workdir}/${BUILD_DIR}/release
 
 
 openwrt_build_configure()
@@ -183,14 +192,7 @@ openwrt_buildprep()
   echo "Installing packages"
   make package/install
 
-# TODO stuff below this point should be in another script
-
-  echo "Compiling your package of choice"
-  make package/internetisdownredirect/compile
-  make package/internetisdownredirect/install
-  make package/index
 }
-
 
 echo "Configure for build."
 for arch in $architectures; do
@@ -201,7 +203,6 @@ echo "Prepare for build"
 for arch in $architectures; do
   openwrt_buildprep ${arch}
 done
-
 
 # Preparation is now completed
 echo "Preparation completed, you may now build the firmware or build single packages."
