refactor clone and patch

diff --git a/build_lib b/build_lib
--- a/build_lib
+++ b/build_lib
@@ -1,7 +1,44 @@
-#
+#!/bin/sh 
 # Library of functions to help build sudowrt firmware.
 # Used by build_pre and build scripts.
 #
+
+set -e
+set -x
+
+BUILD_DIR=built_firmware
+params=($*)
+
+validate() {
+  reclone=0
+  architecture=$1
+
+  if [ -z "${architecture}" ]; then
+    echo "Usage: ./build <architecture>"
+    echo " "
+    echo " "
+    echo "Example:"
+    echo " "
+    echo "  ./build ar71xx"
+    echo "or"
+    echo "  ./build atheros"
+    echo " "
+    exit 1
+  fi
+
+  echo "Checking working directory"
+  if [[ ! -d openwrt_config ]]; then
+    echo "Invalid working directory!"
+    exit 1
+  fi
+
+  validate_architecture $architecture
+}
+
+validate params
+
+# Create list of packages to build
+all_packages="$(cat openwrt_config/packages)"
 
 validate_architecture() {
   arch_requested=$1
@@ -29,6 +66,104 @@ validate_architecture() {
     echo "  Architecture must be in openwrt_config/architectures"
     exit 1
   fi
+}
+
+openwrt_clone_and_patch() {
+  # Add the git commit hash and build date to the firmware
+  build_number="$(git log --pretty=format:'%H' -n 1)"
+  mkdir -p files/opt/sudowrt
+  echo "$build_number | built on $(date)" > files/opt/sudowrt/build_version
+
+  workdir=$(pwd)
+  mkdir -p ${BUILD_DIR}
+
+  openwrt_version=$(cat openwrt_config/version)
+  openwrt_path=$(echo "${openwrt_version}" | cut -d ':' -f 1)
+  openwrt_rev=$(echo "${openwrt_version}" | cut -d ':' -f 2)
+
+  OPENWRT_CHECKOUT_DIR="${workdir}/${BUILD_DIR}/openwrt"  
+    
+  echo "Removing and re-cloning openwrt build root";
+
+  echo "OpenWRT path: ${openwrt_path}"
+  echo "OpenWRT revision: ${openwrt_rev}"
+  echo "Checking out OpenWRT into ${BUILD_DIR}, this could take some time"
+
+  rm -rf "${OPENWRT_CHECKOUT_DIR}"
+  git clone "git://git.openwrt.org/${openwrt_path}/openwrt.git" "${OPENWRT_CHECKOUT_DIR}"
+  cd "${OPENWRT_CHECKOUT_DIR}"
+  git checkout "${openwrt_rev}"
+  cd "${workdir}"
+
+  if [ $? -ne 0 ]; then
+    echo "Error during svn checkout of OpenWRT"
+    exit $?
+  fi
+
+  if [ -d "openwrt_addons" ] ; then
+    echo "Adding extra files."
+    cp -r openwrt_addons/* "${OPENWRT_CHECKOUT_DIR}"
+  fi
+
+  # Remove configuration file already present in the generic build dir
+  rm -f "${workdir}/${BUILD_DIR}/openwrt/.config"
+
+  # Inject feeds and configurations
+  echo "Configuring feeds"
+
+  feedlines=()
+  feed_file="${workdir}/openwrt_config/feeds"
+  while read -r line
+  do
+    feedlines=("${feedlines[@]}" "${line}")
+  done < "$feed_file"
+
+  feed_titles=()
+  feed_sources=()
+  for feedline in "${feedlines[@]}"; do
+    IFS=: read -a ARRAY <<< "${feedline}"
+    feed_title=${ARRAY[*]:0:1}
+    feed_titles=("${feed_titles[@]}" "${feed_title}")
+
+    SAVE_IFS=$IFS
+    IFS=":"
+    feed_source="${ARRAY[*]:1}"
+    IFS=$SAVE_IFS
+
+    feed_sources=("${feed_sources[@]}" "${feed_source}")
+  done
+
+  cat /dev/null > "${OPENWRT_CHECKOUT_DIR}/feeds.conf"
+  for feed_source in "${feed_sources[@]}"; do
+    echo "${feed_source}"  >> "${OPENWRT_CHECKOUT_DIR}/feeds.conf"
+  done
+
+  echo "Applying patches for OpenWRT base tree..."
+  cd "${OPENWRT_CHECKOUT_DIR}"
+  if [ ! -h "patches" ] ; then
+    ln -s "${workdir}/openwrt_patches" patches
+  fi
+  if [ ! -f "patches/series" ] ; then
+    quilt import patches/*
+  fi
+
+  quilt push -f -a -q || [ $? -eq 2 ] #quilt returns a 2 if there is nothing more to do
+
+  cd "${OPENWRT_CHECKOUT_DIR}"
+
+  # Importing feeds
+  echo "Importing feeds"
+  ./scripts/feeds update -a > /dev/null
+
+  for pkg in ${all_packages}; do
+    # Check if package name begins with a minus
+    if [[ ${pkg:0:1} != "-" ]]; then
+      ./scripts/feeds install "${pkg}"
+     fi
+  done
+
+  # change back to initial directory
+  cd "${workdir}"
 }
 
 openwrt_build_configure()
