build_lib refactoring

diff --git a/build_lib b/build_lib
--- a/build_lib
+++ b/build_lib
@@ -8,6 +8,8 @@ set -x
 
 BUILD_DIR=built_firmware
 workdir=$(pwd)
+OPENWRT_CHECKOUT_DIR="${workdir}/${BUILD_DIR}/openwrt"  
+
 params=($*)
 
 validate_architecture() {
@@ -66,47 +68,9 @@ validate $params
 # Create list of packages to build
 all_packages="$(cat openwrt_config/packages)"
 
-openwrt_clone_and_patch() {
-  # Add the git commit hash and build date to the firmware
-  build_number="$(git log --pretty=format:'%H' -n 1)"
-  mkdir -p files/opt/sudowrt
-  echo "$build_number | built on $(date)" > files/opt/sudowrt/build_version
-
-  mkdir -p "${workdir}/${BUILD_DIR}"
-
-  openwrt_version=$(cat openwrt_config/version)
-  openwrt_path=$(echo "${openwrt_version}" | cut -d ':' -f 1)
-  openwrt_rev=$(echo "${openwrt_version}" | cut -d ':' -f 2)
-
-  OPENWRT_CHECKOUT_DIR="${workdir}/${BUILD_DIR}/openwrt"  
-    
-  echo "Removing and re-cloning openwrt build root";
-
-  echo "OpenWRT path: ${openwrt_path}"
-  echo "OpenWRT revision: ${openwrt_rev}"
-  echo "Checking out OpenWRT into ${BUILD_DIR}, this could take some time"
-
-  rm -rf "${OPENWRT_CHECKOUT_DIR}"
-  git clone "git://git.openwrt.org/${openwrt_path}/openwrt.git" "${OPENWRT_CHECKOUT_DIR}"
-  cd "${OPENWRT_CHECKOUT_DIR}"
-  git checkout "${openwrt_rev}"
-  cd "${workdir}"
-
-  if [ $? -ne 0 ]; then
-    echo "Error during svn checkout of OpenWRT"
-    exit $?
-  fi
-
-  if [ -d "openwrt_addons" ] ; then
-    echo "Adding extra files."
-    cp -r openwrt_addons/* "${OPENWRT_CHECKOUT_DIR}"
-  fi
-
-  # Remove configuration file already present in the generic build dir
-  rm -f "${workdir}/${BUILD_DIR}/openwrt/.config"
-
+openwrt_feeds_configure() {
   # Inject feeds and configurations
-  echo "Configuring feeds"
+  echo "Configuring feeds..."
 
   feedlines=()
   feed_file="${workdir}/openwrt_config/feeds"
@@ -135,17 +99,10 @@ openwrt_clone_and_patch() {
     echo "${feed_source}"  >> "${OPENWRT_CHECKOUT_DIR}/feeds.conf"
   done
 
-  echo "Applying patches for OpenWRT base tree..."
-  cd "${OPENWRT_CHECKOUT_DIR}"
-  if [ ! -h "patches" ] ; then
-    ln -s "${workdir}/openwrt_patches" patches
-  fi
-  if [ ! -f "patches/series" ] ; then
-    quilt import patches/*
-  fi
+  echo "Configuring feeds done."
+}
 
-  quilt push -f -a -q || [ $? -eq 2 ] #quilt returns a 2 if there is nothing more to do
-
+openwrt_feeds_import() {
   cd "${OPENWRT_CHECKOUT_DIR}"
 
   # Importing feeds
@@ -158,6 +115,59 @@ openwrt_clone_and_patch() {
       ./scripts/feeds install "${pkg}"
      fi
   done
+}
+
+openwrt_clone_and_patch() {
+  # Add the git commit hash and build date to the firmware
+  build_number="$(git log --pretty=format:'%H' -n 1)"
+  mkdir -p files/opt/sudowrt
+  echo "$build_number | built on $(date)" > files/opt/sudowrt/build_version
+
+  mkdir -p "${workdir}/${BUILD_DIR}"
+
+  openwrt_version=$(cat openwrt_config/version)
+  openwrt_path=$(echo "${openwrt_version}" | cut -d ':' -f 1)
+  openwrt_rev=$(echo "${openwrt_version}" | cut -d ':' -f 2)
+  
+  echo "Removing and re-cloning openwrt build root";
+
+  echo "OpenWRT path: ${openwrt_path}"
+  echo "OpenWRT revision: ${openwrt_rev}"
+  echo "Checking out OpenWRT into ${BUILD_DIR}, this could take some time"
+
+  rm -rf "${OPENWRT_CHECKOUT_DIR}"
+  git clone "git://git.openwrt.org/${openwrt_path}/openwrt.git" "${OPENWRT_CHECKOUT_DIR}"
+  cd "${OPENWRT_CHECKOUT_DIR}"
+  git checkout "${openwrt_rev}"
+  cd "${workdir}"
+
+  if [ $? -ne 0 ]; then
+    echo "Error during svn checkout of OpenWRT"
+    exit $?
+  fi
+
+  if [ -d "openwrt_addons" ] ; then
+    echo "Adding extra files."
+    cp -r openwrt_addons/* "${OPENWRT_CHECKOUT_DIR}"
+  fi
+
+  # Remove configuration file already present in the generic build dir
+  rm -f "${workdir}/${BUILD_DIR}/openwrt/.config"
+
+  openwrt_feeds_configure
+ 
+  echo "Applying patches for OpenWRT base tree..."
+  cd "${OPENWRT_CHECKOUT_DIR}"
+  if [ ! -h "patches" ] ; then
+    ln -s "${workdir}/openwrt_patches" patches
+  fi
+  if [ ! -f "patches/series" ] ; then
+    quilt import patches/*
+  fi
+
+  quilt push -f -a -q || [ $? -eq 2 ] #quilt returns a 2 if there is nothing more to do
+
+  openwrt_feeds_import
 
   # change back to initial directory
   cd "${workdir}"
@@ -261,11 +271,8 @@ openwrt_builder()
 openwrt_image_rebuilder()
 {
   local arch=$1
-  local openwrt_checkout_dir=${workdir}/${BUILD_DIR}/openwrt
   local files_dir=${workdir}/files
   local build_dir=${workdir}/${BUILD_DIR}/builder.${arch}
-  local kconfig=${workdir}/${BUILD_DIR}/openwrt/scripts/kconfig.pl
-  local config_dir=${workdir}/openwrt_config/arch_configs
   local config=${build_dir}/.config
 
   if [ ! -d "${build_dir}" ]; then
@@ -273,47 +280,8 @@ openwrt_image_rebuilder()
     exit 1
   fi
 
-  echo "Configuring feeds"
-  
-  feedlines=()
-  feed_file="${workdir}/openwrt_config/feeds"
-  while read -r line
-  do
-      feedlines=("${feedlines[@]}" "${line}")
-  done < "$feed_file"
-  
-  feed_titles=()
-  feed_sources=()
-  for feedline in "${feedlines[@]}"; do
-      IFS=: read -a ARRAY <<< "${feedline}"
-      feed_title=${ARRAY[*]:0:1}
-      feed_titles=("${feed_titles[@]}" "${feed_title}")
-      
-      SAVE_IFS=$IFS
-      IFS=":"
-      feed_source="${ARRAY[*]:1}"
-      IFS=$SAVE_IFS
-      
-      feed_sources=("${feed_sources[@]}" "${feed_source}")
-  done
-
-  cat /dev/null > ${openwrt_checkout_dir}/feeds.conf
-  for feed_source in "${feed_sources[@]}"; do
-      echo "${feed_source}"  >> ${openwrt_checkout_dir}/feeds.conf
-  done
-
-  cd ${openwrt_checkout_dir}
-
-  # Importing feeds
-  echo "Importing feeds"
-  ./scripts/feeds update -a > /dev/null
-
-  for pkg in ${all_packages}; do
-      # Check if package name begins with a minus
-      if [[ ${pkg:0:1} != "-" ]]; then
-          ./scripts/feeds install ${pkg}
-      fi
-  done
+  openwrt_feeds_configure
+  openwrt_feeds_import
 
   cd ${build_dir}
 
@@ -326,20 +294,7 @@ openwrt_image_rebuilder()
   # Copy files
   cp -a ${files_dir} ${build_dir}
 
-  echo "Generating config file"
-  # Include generic and arch-specific config options in config file
-  $kconfig 'm+' ${config_dir}/generic ${config_dir}/${arch} > ${config}
-
-  # Include all common packages
-  for pkg in ${all_packages}; do
-    # Check if package name begins with a minus
-    if [[ ${pkg:0:1} == "-" ]]; then
-      pkg=${pkg:1:${#pkg}-1} # strip first character
-      echo "CONFIG_PACKAGE_${pkg}=n" >> ${config}
-    else
-      echo "CONFIG_PACKAGE_${pkg}=y" >> ${config}      
-    fi
-  done
+  openwrt_build_configure $arch
 
   # Complete config file generation
   cd ${build_dir}
