rework build process related to #116 and #137

diff --git a/build_lib b/build_lib
--- a/build_lib
+++ b/build_lib
@@ -10,7 +10,7 @@ BUILD_DIR=built_firmware
 workdir=$(pwd)
 OPENWRT_CHECKOUT_DIR="${workdir}/${BUILD_DIR}/openwrt"  
 
-params=($*)
+params="$@"
 SYSTEM_CORES=$(cat /proc/cpuinfo | grep bogomips | wc -l)
 
 validate_architecture() {
@@ -43,6 +43,7 @@ validate_architecture() {
 
 validate() {
   architecture=$1
+  target=$2
 
   if [ -z "${architecture}" ]; then
     echo "Usage: ${0} <architecture>"
@@ -186,9 +187,6 @@ openwrt_build_configure()
   local config_dir=${workdir}/openwrt_config/arch_configs
   local config=${workdir}/${BUILD_DIR}/openwrt/config.${arch}
   $kconfig 'm+' "${config_dir}/generic" "${config_dir}/${arch}" > "${config}"
-  #echo "CONFIG_TARGET_ar71xx_generic_MYNETN600=y" >> "${config}"
-  #echo "CONFIG_TARGET_ar71xx_generic_MYNETN750=y" >> "${config}"
-  #echo "CONFIG_HAS_SUBTARGETS=y" >> "${config}"
 
   # Include all common packages
   for pkg in ${all_packages}; do
@@ -252,10 +250,6 @@ openwrt_buildprep()
 
   # download dependencies (tools, toolchain, packages, feeds)
   make download
-  make package/libs/lzo/download V=s
-  make package/libs/ncurses/download V=s
-  make package/utils/util-linux/download V=s
-  make package/feeds/openwrt/attr/download V=s
 
   # find all dependencies in package directory and force download them, related to issue #116
   #for d in $(find package/ -mindepth 1 -maxdepth 2 -type d); do
@@ -311,4 +305,52 @@ openwrt_builder()
   clean_confdir3_leftover "${build_dir}/build_dir/host/findutils-4.4.2"
   
   echo "Building [${arch}] done."
+}
+
+remove_images() 
+{
+  local image_dir=$1
+  if [ -e ${image_dir} ]; then
+    rm -r ${image_dir}
+  else
+    echo "Warning: ${image_dir} not found, maybe this is an initial build"
+  fi
+}
+
+openwrt_rebuilder()
+{
+
+  BUILD_CORES=$(($SYSTEM_CORES * 2))
+  if [ -v $SUDOWRT_DEBUG ]; then
+    BUILD_CORES=1
+  fi
+
+  local arch=$1
+  local target=$2
+
+  # Rebuild any changes made to openwrt_configs
+  local build_dir=${workdir}/${BUILD_DIR}/builder.${arch}
+  local kconfig=${build_dir}/scripts/kconfig.pl
+  local config_dir=${workdir}/openwrt_config/arch_configs
+  local config=${build_dir}/config.${arch}
+  $kconfig 'm+' "${config_dir}/generic" "${config_dir}/${arch}" > "${config}"
+
+  cp ${config} ${build_dir}/.config
+  make defconfig -C ${build_dir} 
+
+  echo "Deleting old binaries in dir: ${build_dir}/bin/${arch}..." 
+  remove_images "${build_dir}/bin/${arch}"
+
+  echo "Rebuilding [${arch}] in dir: ${build_dir}..."  
+
+  make -j$BUILD_CORES -C "${build_dir}" 2>&1 | tee -a "${build_dir}/build.log"
+
+  if [ "$?" != "0" ]; then
+    echo "Rebuilding [${arch}] failed. See ${build_dir}/build.log for details!"
+    exit 1
+  fi
+
+  clean_confdir3_leftover "${build_dir}/build_dir/host/findutils-4.4.2"
+  
+  echo "Rebuilding [${arch}] done."
 }
